spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres

  data:
    mongodb:
      host: mongodb
      port: 27017
      database: product_images

  servlet:
    multipart:
      enabled: true
      max-file-size: 256MB
      max-request-size: 256MB