spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  data:
    mongodb:
      host: localhost
      port: 27017
      database: product_images
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      enabled: true
      max-file-size: 256MB
      max-request-size: 256MB
