spring:
    application:
        name: miracles_store
    jpa:
        hibernate:
            ddl-auto: validate
    liquibase:
        change-log: db/changelog/main-changelog.yml
    profiles:
        active: local