jwt:
    secret: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
    lifetime: 30m
spring:
    application:
        name: miracles_store
    jpa:
        hibernate:
            ddl-auto: validate
    liquibase:
        change-log: db/changelog/main-changelog.yml
